"""empty message

Revision ID: cb6fda08da51
Revises: 13cf25e4b4e7
Create Date: 2020-07-28 00:14:08.791906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb6fda08da51'
down_revision = '13cf25e4b4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productsmeta', sa.Column('numOfComments', sa.Integer(), nullable=True))
    op.drop_column('productsmeta', 'upvotes')
    op.drop_column('productsmeta', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productsmeta', sa.Column('downvotes', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('productsmeta', sa.Column('upvotes', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('productsmeta', 'numOfComments')
    # ### end Alembic commands ###
