"""empty message

Revision ID: ff076c8c80ea
Revises: 999bdbe4e026
Create Date: 2020-08-01 17:58:27.845717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff076c8c80ea'
down_revision = '999bdbe4e026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'total_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
